#/usr/bin/expect -f

set ip [lindex $argv 0];
set port [lindex $argv 1];
set protocol [lindex $argv 2];
set source [lindex $argv 3];
set param [lindex $argv 4];
set graph_data [lindex $argv 5];
set start_end [lindex $argv 6];
set expected_msg [lindex $argv 8];
set expected_path [lindex $argv 9];

set timeout -1

spawn ./client $ip $port $protocol

expect "Источник данных (1 - файл; 2 - клавиатура):"
send "$source\r"

if {$source == "1"} {
	expect "Введите путь к файлу:"
	send "$param\r"
}

if {$source == "2"} {
	expect "Введите количество вершин:"
	send "$param\r"

	if { [string match "* *" $graph_data] } {
		set lines [split $graph_data "|"]
		set line_number 1
		foreach line $lines {
			expect "Введите строку $line_number:"
			send "$line\r"
			incr line_number

			sleep 0.01
		}
		expect "Введите начальную и конечную вершины:"
		send "$start_end\r"
	}
}

expect {
	"\nРезультат: $expected_msg\nКратчайший путь: $expected_path\n" {
		exit 0
	}

	"\nРезультат: \nКратчайший путь: \n" {
		puts "\n"
		exit 1
	}	

	"\nНекорректный формат ввода графа\n" {
		puts "\nОшибка: некорректный формат ввода графа"
		exit 1
	}
	
	"\nНекорректная матрица смежности\n" {
		puts "\nОшибка: некорректная матрица смежности"
		exit 1
	}

	timeout {
		puts "\nОшибка: время ожидания истекло"
		exit 1
	}

	eof {
		puts "\nОшибка: процесс клиента внезапно завершился"
		exit 1
	}		
}
